### ISSUE TITLE
Installing DPDK on Docker/Alpine Linux

### ISSUE THREAD

**Issue by m-peko** [ceph/dpdk#2]
Hi,

I am trying to install DPDK on Alpine Linux but obviously (since it doesn't support Alpine Linux) I have some troubles.

Here are my steps:

1. `docker pull alpine`
2. `docker run -it alpine /bin/sh`
3. `wget https://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz`
4. `tar -xzf glibc-2.28.tar.gz`
5. `cd glibc-2.28`
6. `mkdir glibc-build`
7. `cd glibc-build`
8. `apk add --no-cache make gcc gawk bison linux-headers libc-dev`
9. `../configure --prefix=/usr \
        --disable-profile --enable-add-ons \
        --libexecdir=/usr/lib --includedir=/usr/include_glibc \
        --with-headers=/usr/include \
        --without-cvs --enable-static-pie`
10. `cat > /etc/ld.so.conf << "EOF" # Begin /etc/ld.so.conf
        /usr/local/lib
        /opt/lib
        /usr/lib
        /usr/lib64
        /usr/libexec
        # End /etc/ld.so.conf
        EOF`
11. `make`
12. `make install`
13. `cd /`
14. `wget https://git.dpdk.org/dpdk-stable/snapshot/dpdk-stable-16.11.8.tar.gz`
15. `tar -xzf dpdk-stable-16.11.8.tar.gz`
16. `cd dpdk-stable-16.11.8`
17. `apk add --no-cache bsd-compat-headers binutils coreutils diffutils gettext bash grep sed texinfo perl`
18. `apk add numactl-dev --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted`
19. `make install T=x86_64-native-linuxapp-gcc`

Please, take note that `glibc` header files are placed in `/usr/include_glibc`.

I am getting following errors:

> make[5]: Nothing to be done for 'depdirs'.
> Configuration done
> == Build lib
> == Build lib/librte_compat
> == Build lib/librte_eal
> == Build lib/librte_eal/common
> == Build lib/librte_eal/linuxapp
> == Build lib/librte_eal/linuxapp/eal
>  CC eal_hugepage_info.o
> /dpdk/dpdk-stable-16.11.8/lib/librte_eal/linuxapp/eal/eal_hugepage_info.c: In function 'clear_hugedir':
> /dpdk/dpdk-stable-16.11.8/lib/librte_eal/linuxapp/eal/eal_hugepage_info.c:229:8: warning: implicit declaration of function 'openat'; did you mean 'popen'? [-Wimplicit-function-declaration]
   fd = openat(dir_fd, dirent->d_name, O_RDONLY);
        ^~~~~~
        popen
> /dpdk/dpdk-stable-16.11.8/lib/librte_eal/linuxapp/eal/eal_hugepage_info.c:229:8: warning: nested extern declaration of 'openat' [-Wnested-externs]
> /dpdk/dpdk-stable-16.11.8/lib/librte_eal/linuxapp/eal/eal_hugepage_info.c:229:39: error: 'O_RDONLY' undeclared (first use in this function)
   fd = openat(dir_fd, dirent->d_name, O_RDONLY);
                                       ^~~~~~~~
> /dpdk/dpdk-stable-16.11.8/lib/librte_eal/linuxapp/eal/eal_hugepage_info.c:229:39: note: each undeclared identifier is reported only once for each function it appears in
> /dpdk/dpdk-stable-16.11.8/lib/librte_eal/linuxapp/eal/eal_hugepage_info.c: In function 'eal_hugepage_info_init':
> /dpdk/dpdk-stable-16.11.8/lib/librte_eal/linuxapp/eal/eal_hugepage_info.c:320:26: warning: implicit declaration of function 'open'; did you mean 'popen'? [-Wimplicit-function-declaration]
   hpi->lock_descriptor = open(hpi->hugedir, O_RDONLY);
                          ^~~~
                          popen
> /dpdk/dpdk-stable-16.11.8/lib/librte_eal/linuxapp/eal/eal_hugepage_info.c:320:26: warning: nested extern declaration of 'open' [-Wnested-externs]
> /dpdk/dpdk-stable-16.11.8/lib/librte_eal/linuxapp/eal/eal_hugepage_info.c:320:45: error: 'O_RDONLY' undeclared (first use in this function)
   hpi->lock_descriptor = open(hpi->hugedir, O_RDONLY);
                                             ^~~~~~~~
> make[7]: *** [/dpdk/dpdk-stable-16.11.8/mk/internal/rte.compile-pre.mk:140: eal_hugepage_info.o] Error 1
> make[6]: *** [/dpdk/dpdk-stable-16.11.8/mk/rte.subdir.mk:63: eal] Error 2
> make[5]: *** [/dpdk/dpdk-stable-16.11.8/mk/rte.subdir.mk:63: linuxapp] Error 2
> make[4]: *** [/dpdk/dpdk-stable-16.11.8/mk/rte.subdir.mk:63: librte_eal] Error 2
> make[3]: *** [/dpdk/dpdk-stable-16.11.8/mk/rte.sdkbuild.mk:80: lib] Error 2
> make[2]: *** [/dpdk/dpdk-stable-16.11.8/mk/rte.sdkroot.mk:127: all] Error 2
> make[1]: *** [/dpdk/dpdk-stable-16.11.8/mk/rte.sdkinstall.mk:86: pre_install] Error 2
> make: *** [/dpdk/dpdk-stable-16.11.8/mk/rte.sdkroot.mk:101: install] Error 2

I tried setting the `CFLAGS` in `mk/target/generic/rte.vars.mk` to `/include_glibc` but it didn't work.

**Comment by m-peko** [comment]
For anyone struggling with this issue, here is the solution as a Dockerfile. Many hacky workarounds need to be made.

```
FROM alpine:latest

ARG DPDK_VER=16.11.8
ARG KERNEL_VER=4.9.4

RUN wget https://git.dpdk.org/dpdk-stable/snapshot/dpdk-stable-$DPDK_VER.tar.gz && \
    tar -xzf dpdk-stable-$DPDK_VER.tar.gz && \
    \
    # Install Alpine packages
    apk add --no-cache make gcc linux-headers bsd-compat-headers binutils coreutils diffutils && \
    apk add --no-cache gettext bash grep sed texinfo perl util-linux vim build-base libexecinfo libexecinfo-dev && \
    apk add --no-cache abuild bc cmake ncurses-dev ca-certificates wget && \
    apk add numactl-dev --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted && \
    \
    # Add following lines / workarounds to header files 
    sed -ie '/int cmsg_type;/a unsigned char __cmsg_data;' /usr/include/bits/socket.h && \
    sed -i.old '1s;^;#include <fcntl.h>\n;' /dpdk-stable-$DPDK_VER/lib/librte_eal/common/include/rte_common.h && \
    sed -ie '/#define _VNIC_DEVCMD_H_/a typedef u32 u_int32_t;' /dpdk-stable-$DPDK_VER/drivers/net/enic/base/vnic_devcmd.h && \
    \
    # Prevent usage of the header files on /usr/include/fortify path by deleting them
    # Instead of them header files from /usr/include path will be used
    rm -rf /usr/include/fortify/* && \
    \
    # Add CFLAGS += -D_GNU_SOURCE to the following Makefiles
    cd /dpdk-stable-$DPDK_VER && \
    sed -ie '/CFLAGS/a CFLAGS += -D_GNU_SOURCE' lib/librte_ring/Makefile && \
    sed -ie '/CFLAGS/a CFLAGS += -D_GNU_SOURCE' lib/librte_mempool/Makefile && \
    sed -ie '/CFLAGS/a CFLAGS += -D_GNU_SOURCE' lib/librte_mbuf/Makefile && \
    sed -ie '/CFLAGS/a CFLAGS += -D_GNU_SOURCE' lib/librte_timer/Makefile && \
    sed -ie '/CFLAGS/a CFLAGS += -D_GNU_SOURCE' lib/librte_net/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_eal/linuxapp/eal/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_ether/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_cryptodev/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_vhost/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_hash/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_lpm/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_acl/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_ip_frag/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_sched/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_distributor/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_kni/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_port/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_table/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_pipeline/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' lib/librte_reorder/Makefile && \
    \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/af_packet/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/bonding/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/cxgbe/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/e1000/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/ena/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/enic/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/fm10k/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/i40e/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/ixgbe/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/bnxt/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/null/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/qede/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/ring/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/virtio/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/vmxnet3/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/net/vhost/Makefile && \
    sed -ie '/CFLAGS += $(WERROR_FLAGS)/a CFLAGS += -D_GNU_SOURCE' drivers/crypto/null/Makefile && \
    \
    # Exclude tests from compiling
    sed -i "/\b\(DIRS\|test\)\b/d" app/Makefile && \
    sed -i "/\b\(DIRS\|test-acl\)\b/d" app/Makefile && \
    sed -i "/\b\(DIRS\|test-pipeline\)\b/d" app/Makefile && \
    sed -i "/\b\(DIRS\|test-pmd\)\b/d" app/Makefile && \
    sed -i "/\b\(DIRS\|cmdline_test\)\b/d" app/Makefile && \
    sed -i "/\b\(DIRS\|proc_info\)\b/d" app/Makefile && \
    sed -i "/\b\(DIRS\|pdump\)\b/d" app/Makefile && \
    cd / && \
    \
    # Install missing Alpine Linux kernel modules
    wget -nv -P /srv https://www.kernel.org/pub/linux/kernel/v4.x/linux-$KERNEL_VER.tar.gz && \
    tar -C /srv -zxf /srv/linux-$KERNEL_VER.tar.gz && \
    cd /srv/linux-$KERNEL_VER && \
    make defconfig && \
    ([ ! -f /proc/1/root/proc/config.gz ] || zcat /proc/1/root/proc/config.gz > .config) && \
    echo 'CONFIG_USB=m' >> .config && \
    echo 'CONFIG_USB_HID=m' >> .config && \
    echo 'CONFIG_USB_SUPPORT=y' >> .config && \
    echo 'CONFIG_USB_COMMON=m' >> .config && \
    echo 'CONFIG_USB_ARCH_HAS_HCD=y' >> .config && \
    echo 'CONFIG_USB_DEFAULT_PERSIST=y' >> .config && \
    echo 'CONFIG_USBIP_CORE=m' >> .config && \
    echo 'CONFIG_USBIP_VHCI_HCD=m' >> .config && \
    echo 'CONFIG_USBIP_VHCI_HC_PORTS=8' >> .config && \
    echo 'CONFIG_USBIP_VHCI_NR_HCS=1' >> .config && \
    echo 'CONFIG_USBIP_HOST=m' >> .config && \
    sed -i'.bak' '/hcd->amd_resume_bug/{s/^/\/\//;n;s/^/\/\//}' ./drivers/usb/core/hcd-pci.c && \
    make oldconfig && \
    make modules_prepare && \
    make modules && \
    make modules_install && \
    make clean && \
    cd / && \
    \
    # Install DPDK
    mkdir /dpdk-build && \
    cd dpdk-stable-$DPDK_VER && \
    make install T=x86_64-native-linuxapp-gcc RTE_KERNELDIR=/srv/linux-$KERNEL_VER DESTDIR=/dpdk-build
```

**Comment by tchaikov** [comment]
FWIW, @m-peko ceph/DPDK is just a fork of its upstream at https://github.com/DPDK/dpdk
